### PR TITLE
Update confy dependency

### PR DESCRIPTION
**Pull request by swalladge**
This has a breaking change;
configuration file locations have changed on macos.
See https://crates.io/crates/directories-next/2.0.0 for details on file locations.

Better to get the breaking change over and done with before too many users start running this on macos.  See also #3

### CODE REVIEW

**Comment by swalladge** [comment]
@nizarmah I thought, while we're here, why not update confy so we don't need to update the docs again right away with the breaking change. :)  Could you checkout this and confirm it works for you with the new file locations on mac?

**Comment by nizarmah** [comment]
@swalladge that was my intention, initially. But when I set `confy = v0.5.0`, I got an error. That kind of confused me to be honest. Since I am extremely new to Rust, I wasn't aware of the `{ git = "<repo_url>" }` trick! 

>  Could you checkout this and confirm it works for you with the new file locations on mac?

I've scheduled this for tomorrow! Personally, it'll be easier to address this over the weekend. I'll gladly provide my review, though, once I've verified it's working as expected 👍🏼 

Thanks for opening the pull request to update confy by the way!

**Comment by swalladge** [comment]
@nizarmah thanks!

> But when I set confy = v0.5.0, I got an error.

Yeah, the maintainers haven't published a release for it yet.  The `git = ...` syntax I used just pulls the latest revision from git, which may be unstable, but seems to work fine for me :)

**Review by nizarmah — APPROVED** [review]
@swalladge LGTM :+1:

I tested this by doing the following:
* Checking out the changes
* Ensuring I don't have `$HOME/Library/Application Support/rs.tempoit/tempoit.toml`
* Running the changes
* Ensuring the default toml configuration has been created in the previously mentioned path, while it fails to login to jira
* Updating the toml configuration with my Jira credentials
* Successfully logging time

**Pull request merged**
